### ISSUE TITLE
[Bug] JEI 30.15.0.121 fails to register GUI overlay on NeoForge 26.2.0.41-beta (NoClassDefFoundError: ContainerScreenEvent$Render$Foreground)

### ISSUE THREAD

**Issue by Notorious-real** [mezz/JustEnoughItems#4406]
### Steps to Reproduce the Bug

Install NeoForge 26.2.0.41-beta on Minecraft 26.2
Install JEI 30.15.0.121 (jei-26.2-neoforge-30.15.0.121.jar)
Launch single-player world
Open inventory — item overlay does not appear, though clicking where the wrench icon should be still opens a menu

### Expected Behavior

Item list overlay renders normally.

### Actual Behavior

Overlay is invisible, but the click-target area still exists; JEI search/recipe lookups still work.

### Extra Notes (Optional)

[latest.log](https://github.com/user-attachments/files/30622126/latest.log)

**Comment by Lavshyak** [comment]
i have the same problem on .121 and .120 too (didnt check logs)

I also noticed that the invisible jei is overlapping part of the creative inventory sometimes

If anyone has it working with 26.2 and Neoforge, please tell me the versions of all this

**Comment by Lavshyak** [comment]
yeah this is really fixed
