### ISSUE TITLE
[Crash]: 1.12.2 JEI causing "java.lang.NoClassDefFoundError: mezz/jei/gui/textures/JeiTextureMap"

### ISSUE THREAD

**Issue by FilthyCasual544** [mezz/JustEnoughItems#3697]
### Steps to Reproduce the Crash

Launching Forge from the official Minecraft launcher, 1.12.2 version.  The crash takes place almost immediately on launch.  I suspect it's maxing out the allotted RAM, though I've assigned it a massive amount already (8G).

### Extra Notes (Optional)

Again, working in Minecraft 1.12.2.

As someone who is a complete noob when it comes to Minecraft modding, Java coding, etc, I was only able to determine that JEI was causing the issue by eliminating mods in batches until only the core dependencies remained.  I'm going to need most solutions explained to me as if I were five years old, especially if it involves codes, arguments, or any thing of that nature.

As I mentioned above, I suspect that JEI, or possibly something else before it, is maxing out the RAM, despite the fact that I've assigned 8G of the stuff to the instance/profile.  Is there some way to reduce the load?  Should I get an older version of JEI? 

Sorry for the trouble.

### Crash Report

https://gist.github.com/Fi1thyCasual/98f138fe9c84f8b69b4a985411981489
